### PR TITLE
added the static library

### PR DESCRIPTION
**Pull request by JonnycatMeow**
@Leather128 please merge

### CODE REVIEW

**Comment by Leather128** [comment]
not sure why you made the `Mac` folder capital, but alright i'll take it

**Comment by JonnycatMeow** [comment]
oh well i can lowcase it if you want

**Comment by MAJigsaw77** [comment]
The static lib isn't needed if there's framework

**Comment by MAJigsaw77** [comment]
.___.

**Comment by JonnycatMeow** [comment]
bruh

**Comment by MAJigsaw77** [comment]
Is true xd

**Pull request merged**
